site_name: entretien-api
site_description: Projeto de desenvolvimento do software para TCC da UFPR no curso TADS. Aplicação de otimização de entrevistas por competência
repo_url: https://github.com/Antonio M. Neto/entretien-rh-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Antonio M. Neto">Antonio M. Neto</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
